---
abstract: 'Utility for XS'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Build-Pluggable-XSUtil
no_index:
  directory:
    - inc
provides:
  Devel::WantXS:
    file: lib/Devel/WantXS.pm
    version: 0
  Devel::XSHelper:
    file: lib/Devel/XSHelper.pm
    version: 0.01
  Module::Build::Pluggable::CheckLib:
    file: lib/Module/Build/Pluggable/CheckLib.pm
    version: 0.01
  Module::Build::Pluggable::XSUtil:
    file: lib/Module/Build/Pluggable/XSUtil.pm
    version: 0.01
requires:
  Devel::CheckCompiler: 0.02
  Devel::CheckLib: 0.04
  Devel::PPPort: 3.19
  Exporter: 0
  ExtUtils::ParseXS: 2.21
  Module::Build::Pluggable: 0.04
  XSLoader: 0.02
  parent: 0
  perl: 5.010001
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
