---
abstract: 'Utility for XS'
author:
  - 'Goro Fuji, is original author of Module::Install::XSUtil.'
build_requires:
  Test::Module::Build::Pluggable: 0
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.0.49, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Build-Pluggable-XSUtil
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
provides:
  Devel::WantXS:
    file: lib/Devel/WantXS.pm
    version: 0
  Devel::XSHelper:
    file: lib/Devel/XSHelper.pm
    version: 1.01
  Module::Build::Pluggable::CheckLib:
    file: lib/Module/Build/Pluggable/CheckLib.pm
    version: 1.01
  Module::Build::Pluggable::XSUtil:
    file: lib/Module/Build/Pluggable/XSUtil.pm
    version: 1.01
requires:
  Devel::CheckCompiler: 0.02
  Devel::CheckLib: 0.04
  Devel::PPPort: 3.19
  Exporter: 0
  ExtUtils::CBuilder: 0
  ExtUtils::ParseXS: 2.21
  Module::Build::Pluggable: 0.04
  Module::Build::Pluggable::Base: 0
  XSLoader: 0.02
  parent: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/tokuhirom/Module-Build-Pluggable-XSUtil/issues
  homepage: https://github.com/tokuhirom/Module-Build-Pluggable-XSUtil
  repository: git://github.com/tokuhirom/Module-Build-Pluggable-XSUtil.git
version: 1.01
x_contributors:
  - 'hideo55 <hide.o.j55@gmail.com>'
  - 'tokuhirom <tokuhirom@gmail.com>'
